export const artistsSearchData = [
  {
    id: 0,
    username: '@AmyAppleseed',
    name: 'Amy Appleseed',
    type: 'profile',
    title: 'Photographer | Videographer',
    location: 'Portland, OR',
    geolocation: {latitude: 45.523064, longitude: -122.676483},
    verified: true,
    connected: false,
    color: 'orange',
    profilePic: '../assets/Photographer-Example.png',
  },
  {
    id: 1,
    username: '@Cannons',
    name: 'Cannons',
    title: 'Band',
    location: 'Houston, TX',
    geolocation: {latitude: 29.749907, longitude: -95.358421},
    verified: true,
    connected: true,
    profilePic: '../assets/Cannons.jpg',
  },
  {
    id: 2,
    username: '@JonnyDrums',
    name: 'Jonny Hopkins',
    title: 'Drummer | Instrumentalist',
    location: 'Newark, NJ',
    geolocation: {latitude: 40.735657, longitude: -74.172363},
    verified: false,
    connected: false,
    profilePic: '../assets/Drummer.jpg',
  },
  {
    id: 3,
    username: '@AdrianMadeIt',
    name: 'Adrian Made It',
    title: 'Producer | Audio Engineer',
    location: 'New York, NY',
    geolocation: {latitude: 40.73061, longitude: -73.935242},
    verified: false,
    connected: false,
    profilePic: '../assets/Producer-Example.png',
  },
  {
    id: 4,
    username: '@DogCreation',
    name: 'Cody Barrett',
    title: 'Musical Artist',
    location: 'Madrid, ES',
    geolocation: {latitude: 40.416775, longitude: -3.70379},
    verified: true,
    connected: true,
    profilePic: '../assets/DogCreation.jpg',
  },
  {
    id: 5,
    username: '@Palace',
    name: 'Palace',
    title: 'Band',
    location: 'London, UK',
    geolocation: {latitude: 51.509865, longitude: -0.118092},
    verified: true,
    connected: false,
    profilePic: '../assets/Palace.jpg',
  },
];
