export const conversations = [
   {
      id: 4,
      username: '@DogCreation',
      name: 'Cody Barrett',
      title: 'Musical Artist',
      location: 'Madrid, ES',
      geolocation: {latitude: 40.416775, longitude: -3.70379},
      verified: true,
      connected: true,
      profilePic: '../assets/DogCreation.jpg',
      latestMessage: 'Say Less!',
      latestMessageDateTime: '1:05 PM',
      latestMessagesRead: true,
      latestMessagesCount: 0,
      latestMessageDelivered: true,
      lastMessageRead: true,
    },
    {
      id: 1,
      username: '@Cannons',
      name: 'Cannons',
      title: 'Band',
      location: 'Houston, TX',
      geolocation: {latitude: 29.749907, longitude: -95.358421},
      verified: true,
      connected: true,
      profilePic: '../assets/Cannons.jpg',
      latestMessage: 'Whats happening!',
      latestMessageDateTime: '11:23 AM',
      latestMessageRead: false,
      latestMessagesCount: 5,
      latestMessageDelivered: false,
      lastMessageRead: true,
    },
 ];
 